In [39]:
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [40]:
# Import Dataset
df=pd.read_csv("census-income (7).csv",skipinitialspace=True)
df.tail()

age     workclass  fnlwgt   education  education-num  \
32556   27       Private  257302  Assoc-acdm             12   
32557   40       Private  154374     HS-grad              9   
32558   58       Private  151910     HS-grad              9   
32559   22       Private  201490     HS-grad              9   
32560   52  Self-emp-inc  287927     HS-grad              9   

           marital-status         occupation relationship   race     sex  \
32556  Married-civ-spouse       Tech-support         Wife  White  Female   
32557  Married-civ-spouse  Machine-op-inspct      Husband  White    Male   
32558             Widowed       Adm-clerical    Unmarried  White  Female   
32559       Never-married       Adm-clerical    Own-child  White    Male   
32560  Married-civ-spouse    Exec-managerial         Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country Unnamed: 14  
32556             0             0              38  United-States       <=50K  
32557             0             0              40  United-States        >50K  
32558             0             0              40  United-States       <=50K  
32559             0             0              20  United-States       <=50K  
32560         15024             0              40  United-States        >50K

In [41]:
df["workclass"].unique()

array(['State-gov', 'Self-emp-not-inc', 'Private', 'Federal-gov',
       'Local-gov', '?', 'Self-emp-inc', 'Without-pay', 'Never-worked'],
      dtype=object)

In [42]:
df["occupation"].unique()

array(['Adm-clerical', 'Exec-managerial', 'Handlers-cleaners',
       'Prof-specialty', 'Other-service', 'Sales', 'Craft-repair',
       'Transport-moving', 'Farming-fishing', 'Machine-op-inspct',
       'Tech-support', '?', 'Protective-serv', 'Armed-Forces',
       'Priv-house-serv'], dtype=object)

In [43]:
df["native-country"].unique()

array(['United-States', 'Cuba', 'Jamaica', 'India', '?', 'Mexico',
       'South', 'Puerto-Rico', 'Honduras', 'England', 'Canada', 'Germany',
       'Iran', 'Philippines', 'Italy', 'Poland', 'Columbia', 'Cambodia',
       'Thailand', 'Ecuador', 'Laos', 'Taiwan', 'Haiti', 'Portugal',
       'Dominican-Republic', 'El-Salvador', 'France', 'Guatemala',
       'China', 'Japan', 'Yugoslavia', 'Peru',
       'Outlying-US(Guam-USVI-etc)', 'Scotland', 'Trinadad&Tobago',
       'Greece', 'Nicaragua', 'Vietnam', 'Hong', 'Ireland', 'Hungary',
       'Holand-Netherlands'], dtype=object)

In [44]:
# Replace special characteristics with Nan values
data= df.replace('?',np.nan)

In [45]:
# Find & Remove null values
data.isnull().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     583
Unnamed: 14          0
dtype: int64

In [46]:
data=data.dropna()

In [47]:
# Rename the unnamed columns
data=data.rename(columns={'Unnamed: 14': 'AnnualIncome'})

In [48]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30162 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             30162 non-null  int64 
 1   workclass       30162 non-null  object
 2   fnlwgt          30162 non-null  int64 
 3   education       30162 non-null  object
 4   education-num   30162 non-null  int64 
 5   marital-status  30162 non-null  object
 6   occupation      30162 non-null  object
 7   relationship    30162 non-null  object
 8   race            30162 non-null  object
 9   sex             30162 non-null  object
 10  capital-gain    30162 non-null  int64 
 11  capital-loss    30162 non-null  int64 
 12  hours-per-week  30162 non-null  int64 
 13  native-country  30162 non-null  object
 14  AnnualIncome    30162 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [49]:
data["education"].unique()

array(['Bachelors', 'HS-grad', '11th', 'Masters', '9th', 'Some-college',
       'Assoc-acdm', '7th-8th', 'Doctorate', 'Assoc-voc', 'Prof-school',
       '5th-6th', '10th', 'Preschool', '12th', '1st-4th'], dtype=object)

In [50]:
data.education= data.education.replace(['Preschool', '1st-4th', '5th-6th', '7th-8th', '9th','10th', '11th', '12th'], 'School')
data.education = data.education.replace(['Assoc-voc', 'Assoc-acdm', 'Prof-school', 'Some-college'], 'Higher')

In [51]:
# Use LabelEncoder to convert object type data to numerical data
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder() 
data["workclass"]=l.fit_transform(data["workclass"])
data["marital-status"]=l.fit_transform(data["marital-status"])
data["occupation"]=l.fit_transform(data["occupation"])
data["relationship"]=l.fit_transform(data["relationship"])
data["race"]=l.fit_transform(data["race"])
data["sex"]=l.fit_transform(data["sex"])
data["education"]=l.fit_transform(data["education"])
data["native-country"]=l.fit_transform(data["native-country"])

In [52]:
# Extract features and target variables  and y
x=data.drop(["AnnualIncome"],axis=1)
y=data['AnnualIncome'].replace('<=50K',0).replace('>50K',1)

In [53]:
data['AnnualIncome']=data['AnnualIncome'].replace('<=50K',0).replace('>50K',1)

In [54]:
# Perform Logistic Regression Model
from sklearn.linear_model import *
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.30,random_state=1)


In [55]:
lo=LogisticRegression()
lo.fit(x_train,y_train)
y_pred=lo.predict(x_test)

In [56]:
from sklearn.metrics import *
accuracy_score(y_pred,y_test)

0.7761078572217924

In [57]:
confusion_matrix(y_pred,y_test)

array([[6393, 1650],
       [ 376,  630]], dtype=int64)

In [58]:
# Perform Decision Tree Model

In [59]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
y_pred_DT=dt.predict(x_test)

In [60]:
accuracy_score(y_test,y_pred_DT)

0.7999778981102884

In [61]:
confusion_matrix(y_pred_DT,y_test)

array([[5865,  906],
       [ 904, 1374]], dtype=int64)

In [62]:
# Perform Random Forest Model

In [63]:
from sklearn.ensemble import RandomForestClassifier
RandomForest=RandomForestClassifier()
RandomForest.fit(x_train,y_train)

RandomForestClassifier()

In [64]:
y_pred_RF=RandomForest.predict(x_test)

In [65]:
accuracy_score(y_pred_RF,y_test)

0.8570007735661399

In [66]:
confusion_matrix(y_pred_RF,y_test)

array([[6320,  845],
       [ 449, 1435]], dtype=int64)

In [67]:
import numpy as np
n_estimators=[int(x) for x in np.linspace(start=0,stop=300,num=15)]
max_features=["auto","sqrt"]
max_depth=[2,4]
min_samples_split=[2,5]
min_samples_leaf=[1,2]
bootstrap=[True,False]

In [68]:
param_grid={"n_estimators":n_estimators,"max_features":max_features,"max_depth":max_depth,"min_samples_split":min_samples_split,"min_samples_split":min_samples_split,"bootstrap":bootstrap}

In [69]:
from sklearn.ensemble import RandomForestClassifier
RandomForest=RandomForestClassifier(random_state=0)

# from sklearn.model_selection import GridSearchCV
# RFGrid=GridSearchCV(estimator=RandomForest,param_grid=param_grid,cv=5,verbose=2,n_jobs=4)


In [70]:
from sklearn.model_selection import RandomizedSearchCV
Random = RandomizedSearchCV(estimator = RandomForest, param_distributions = param_grid, n_iter = 2, cv = 2, verbose=0, random_state=100 , n_jobs = -1)

In [71]:
Grid=Random.fit(x_train,y_train)

C:\Users\Bhavanasri\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:427: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(


In [72]:
Random.best_params_

{'n_estimators': 192,
 'min_samples_split': 5,
 'max_features': 'auto',
 'max_depth': 2,
 'bootstrap': True}

In [73]:
from sklearn.ensemble import RandomForestClassifier
RandomForest=RandomForestClassifier(n_estimators=192)
RandomForest.fit(x_train,y_train)

RandomForestClassifier(n_estimators=192)

In [74]:
y_pred_RF=RandomForest.predict(x_test)


In [75]:
accuracy_score(y_pred_RF,y_test)

0.8558956790805614

In [76]:
confusion_matrix(y_pred_RF,y_test)

array([[6302,  837],
       [ 467, 1443]], dtype=int64)